name: Compute latest CV
  
on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create main TeX file
      run: |
        curl https://perso.liris.cnrs.fr/nbarret/generate.php > CV-barret.tex
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@latest
      with:
          root_file: CV-barret.tex
    - name: Move CV to docs
      run: |
        mv -f CV-barret.tex docs/CV-barret.tex
        mv -f CV-barret.pdf docs/CV-barret.pdf
    - name: Push generated CV
      run: |
          git config --global user.name 'Nelly Barret'
          git config --global user.email 'nelly.barret@insa-lyon.fr'
          git add docs/*.tex
          git add docs/*.pdf
          git commit -m "Automated CV generation"
          git push
