name: Compute latest CV
  
on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create main TeX file
      run: |
        cd docs/
        curl https://perso.liris.cnrs.fr/nbarret/generate.php > CV-barret.tex
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@latest
      with:
          root_file: docs/CV-barret.tex
